### ISSUE TITLE
Get Description and Languages from DB

### ISSUE THREAD

**Issue by dtsrkb** [computationalmystic/augur-group7#5]
We are attempting to retrieve the description and Language data from projects using Augur. This will involve a python function that accesses the database and pulls the appropriate information to display on the introduction page component. There are plenty of examples of python code pulling from databases that we can go off of:

```python
class GHTorrent(object):
    """Uses the GHTorrent database to return dataframes with interesting GitHub indicators"""

    def __init__(self, user, password, host, port, dbname):
        """
        Connect to GHTorrent

        :param dbstr: The [database string](http://docs.sqlalchemy.org/en/latest/core/engines.html) to connect to the GHTorrent database
        """
        self.DB_STR = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(
            user, password, host, port, dbname
        )
        logger.debug('GHTorrent: Connecting to {}:{}/{} as {}'.format(host, port, dbname, user))
        self.db = s.create_engine(self.DB_STR, poolclass=s.pool.NullPool)
        try:
            self.userid('howderek')
        except Exception as e:
            logger.error("Could not connect to GHTorrent database. Error: " + str(e))

```
This is an example of some python code retrieving from a DB ^^^^

**Comment by dtsrkb** [comment]
The SQL code for retrieving this information from the database is  finished and refined. There is still no way for us to take this info and display it on the frontend.

**Comment by EricNMitchell** [comment]
New chart files were created that pull the data from the endpoints created in the AugurApi.js file. These chart files are called within the IntroductionPage.vue file on the front end and now display the raw data in lists on the UI.

**Comment by EricNMitchell** [comment]
For the record, the new chart files are DescriptionList.vue and LanguageList.vue
