### ISSUE TITLE
Parse and format issue data to match existing Augur metric formatting

### ISSUE THREAD

**Issue by EricNMitchell** [computationalmystic/augur-group7#6]
We plan to obtain the raw issue data from the github API to send to the frontend, however this data will need to be parsed and formatted to display in a list in the Introduction Tab. Ideally this data would be formatted to match the the style of existing metrics within Augur.

**Comment by sgoggins** [comment]
This seems like a good idea of what you need to do, and where it would end up. Seems good.

**Comment by dtsrkb** [comment]
We have a rough outline of a new data chart that will take in the selected information from the database and display it on the introduction component. This is not yet working, but so far it is in line with the format of the other Augur charts.

**Comment by EricNMitchell** [comment]
The new chart files are working and data is now being displayed on the UI under the Introduction Tab. CSS styling has been added so that the data is listed in relation to the Headers for each dataset

**Comment by EricNMitchell** [comment]
the above comment was in relation to the Language and Description formatting, which was implemented last night. As of today we have raw URL data for the 5 most recent issues that displays on the UI, and we are working to get this data formatted

**Comment by ljakuboski** [comment]
Issue data is retrieved and listed as links. Link does not take user to the issue page and just reloads current github introduction tab.

**Comment by ljakuboski** [comment]
The url links now takes the user to the correct Github location.

**Comment by dtsrkb** [comment]
We matched the link css with the existing augur css
